{"uid":"f757f7e799214bb3","name":"Log in to app","fullName":"Trello UI Login: Log in to app","historyId":"3be2770b2607b06c381ef24d0f10cf60","time":{"start":1655936623093,"stop":1655936659330,"duration":36237},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \n\n","statusTrace":"  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"tests/gui/steps/login_steps.py\", line 9, in step_impl\n    context.login_page.login(context.username, context.password)\n  File \"/Users/runner/work/bootcamp04-trello/bootcamp04-trello/main/trello/gui/page_objects/login_page.py\", line 17, in login\n    self.driver.wait_for_invisibility_of_element_located(self.password_input)\n  File \"/Users/runner/work/bootcamp04-trello/bootcamp04-trello/main/core/selenium/WebDriverUtils.py\", line 119, in wait_for_invisibility_of_element_located\n    return WebDriverWait(self.driver, TIMEOUT).until(\n  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \n\n","statusTrace":"  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"tests/gui/steps/login_steps.py\", line 9, in step_impl\n    context.login_page.login(context.username, context.password)\n  File \"/Users/runner/work/bootcamp04-trello/bootcamp04-trello/main/trello/gui/page_objects/login_page.py\", line 17, in login\n    self.driver.wait_for_invisibility_of_element_located(self.password_input)\n  File \"/Users/runner/work/bootcamp04-trello/bootcamp04-trello/main/core/selenium/WebDriverUtils.py\", line 119, in wait_for_invisibility_of_element_located\n    return WebDriverWait(self.driver, TIMEOUT).until(\n  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"Given the user goes to \"/login\"","time":{"start":1655936626074,"stop":1655936628375,"duration":2301},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When the user sends its credentials","time":{"start":1655936628376,"stop":1655936658494,"duration":30118},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \n\n","statusTrace":"  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"tests/gui/steps/login_steps.py\", line 9, in step_impl\n    context.login_page.login(context.username, context.password)\n  File \"/Users/runner/work/bootcamp04-trello/bootcamp04-trello/main/trello/gui/page_objects/login_page.py\", line 17, in login\n    self.driver.wait_for_invisibility_of_element_located(self.password_input)\n  File \"/Users/runner/work/bootcamp04-trello/bootcamp04-trello/main/core/selenium/WebDriverUtils.py\", line 119, in wait_for_invisibility_of_element_located\n    return WebDriverWait(self.driver, TIMEOUT).until(\n  File \"/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true},{"name":"Then the user should be logged in","time":{"start":1655936659330,"stop":1655936659330,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":3,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Trello UI Login"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"f757f7e799214bb3.json","parameterValues":[]}